[package]
name = "ipcalc"
version = "0.1.0"
edition = "2021"
description = "ipcalc provides a simple way to display information about an IP and its network"
license = "MIT"

[dependencies]
clap = { version = "4.3.22", features = ["derive"] }
