name: ci
on:
  pull_request:
  push:
    branches:
    - main
jobs:
  test:
    name: test
    runs-on: "ubuntu-latest"
    env:
      TARGET_DIR: ./target
      RUST_BACKTRACE: 1
    steps:
      - name: "checkout code"
        uses: actions/checkout@v2
      - name: "install rust"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: "build application"
        run: cargo build --verbose
      - name: "run tests"
        run: make test-unit

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: "checkout code"
        uses: actions/checkout@v2
      - name: "install rust"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: rustfmt
      - name: "check formatting"
        run: make test-style
      - name: "check linting"
        run: make test-lint
