name: release
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build:
    name: "build release"
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout code"
        uses: actions/checkout@v2
      - name: "install rust"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: "build application"
        run: VERSION=${{ github.ref_name }} cargo build --verbose --release
      - name: "get github release metadata"
        id: get_release
        uses: bruceadams/get-release@v1.2.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: "upload release to github"
        uses: actions/upload-release-asset@v1
        id: upload_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./target/release/ipcalc
          asset_name: ipcalc-linux-amd64-${{ github.ref_name }}
          asset_content_type: application/octet-stream
